name: E2E Test

on:
    push:
        branches: ['test/e2e']
    pull_request:
        branches: ['test/e2e']

jobs:
    e2e:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '16'
            - name: Bring up WordPress
              run: docker-compose -f __tests__/e2e/docker-compose.yml up --build -d
            - name: Wait for DB import
              run: |
                echo 'pausing: waiting for mysql to come available'
                ./__tests__/e2e/wait-for-mysql.sh
                echo 'un-pausing: mysql is now available'
            - name: Activate WP plugins
              run: |
                docker exec e2e_wordpress_1 wp --allow-root plugin activate "Basic-Auth-master/basic-auth"
                docker exec e2e_wordpress_1 wp --allow-root plugin activate "wp-plugin"
            - name: Install Dependencies
              run: yarn install
            - name: Run end-to-end test
              run: yarn test e2e.spec.ts
